version: '3.3'

services:
  db: 
    image: mongo:3.4
  backend:
    image: node:18-buster-slim
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    command: bash -c "cd /backend && npm i && node app"
  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
      - 80:80
